# Generated by Django 3.0 on 2019-12-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='Please enter publisher detalis', max_length=220),
        ),
    ]
